### ISSUE TITLE
Ability to choose db connection at runtime

### ISSUE THREAD

**Issue by gautamk** [groveco/django-sql-explorer#115]
Instead of deploying multiple instances of this application the ability to choose the db connection at run-time would be great.

**Comment by gautamk** [comment]
I'm currently building this feature in my fork

**Comment by chrisclark** [comment]
@gautamk sorry for the slow response here -- yes, definitely interested. Can't promise I will merge it right away, but by all means open a PR and let's talk about it! Thanks.

**Comment by chrisclark** [comment]
@gautamk any chance you are still working on this? I took a glance at your fork and it looks promising. If it has been working for you, I would love to get a PR open and start working to merge it. Thanks!

**Comment by gautamk** [comment]
@chrisclark I ended up writing a simple SQL Explorer with flask to solve this problem, unfortunately it's proprietary code and I don't have access to it at the moment, but it was simple enough that I wrote it over a weekend. It was missing a lot of security and export features available here.

**Comment by mykljohn** [comment]
We are not able to set up users with read only permission, so this would be great because I can clone the DB and point explorer to the clone.

**Comment by chrisclark** [comment]
I hear ya. Open to PRs for this feature for sure. On the other hand, in
this situation, there should be no reason you can't just point Explorer to
the clone. The connection is totally configurable via settings (documented
in readme.md). This feature is specifically to allow multiple *different*
connections within the same explorer instance. You should have no trouble
just telling explorer to use the cloned DB.

On Wed, Jun 15, 2016 at 7:40 PM, mykljohn <notifications@github.com> wrote:

> We are not able to set up users with read only permission, so this would
> be great because I can clone the DB and point explorer to the clone.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/groveco/django-sql-explorer/issues/115#issuecomment-226374110>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAqVxCklARQMBxCJqs8vKVjJgexI3ahwks5qMLeqgaJpZM4EPEkw>
> .
>



-- 

Chris Clark │ Grove Co. │ 617-571-7327

1770 Union St, San Francisco, CA

**Comment by mykljohn** [comment]
Oh, OK thanks

**Comment by spapas** [comment]
Hello, what is the status of this enchancement? Is anybody working on it? This would be really useful for me but with a number of changes.

In my environment we have a large (more than 15) number of django apps each one with its own business users. Ideall I'd like to integrate most of them with django-sql-explorer to allow quick and dirty custom queries without the need to add special views. This won't be easy to do since I'd need to add the app requirement to all of these and, if if I wanted to have the full capabilities of django-sql-explorer (for example installing celery or integrating email to all these apps) would be even more difficult! So the ideal solution would be to create a stand alone django-sql-explorer web app (not tightly related to any existing application) that would be used to connect and query all the existing django applications (and maybe also query other, *non-django* database connections). For this we'd need to define a number of database connections and relate each query with its corresponding connection.

Also, for each of these databases we'd like to have different users - i.e some users will have query access to database1/djangoapp1, some other users query access to database2/djangoapp2 etc. So the ideal would be to allow the user definining database connections through a model and relating instances of that model with the correct users (through a M2M relation with either QUERY_READ or QUERY_CREATE access). 

One problem with this approach is that I'm not really sure if it is possible to create django database connections on the fly -- from the docs it seems that you need to define any database connections through the settings.py thus the connection should be handled at a lower level that django :/ 

What do you propose?

**Comment by spapas** [comment]
After some research, I have come to the conclusion that the django ORM can connect to databases that are defined *only* through settings. Thus, my idea of defining each possible connection in a model is not possible :(

What is possible and could be a nice first step towards my goal is to add an optional ``connection = CharField(blank=True, null=True)`` to the ``explorer.models.Query`` model that, if is not blank will tie that query to the database connection with that name (which must exist in settings.py of course). If the connection is blank then Query will retain the same behavior. If there are not any objections I can provide a PR for that functionality.

After we have the multi-database functionality we can start thinking about access rights for each one of the multi-databases.

**Comment by jameswinegar** [comment]
I would love to be able to deploy this tool to analysts. This would require the ability to choose between a set of DB connections. Let me know if I can help @spapas.

**Comment by spapas** [comment]
Hello @jameswinegar, I think the first step for this is to add the optional ``connection`` field to the ``Query`` model and, if it exists use this connection attribute for that query instance. This seems simple enough to me.

Another nice addition would be to use a ``choices`` for the connection that would be filled from the ``settings.DATABASES`` so the users create the query will just pick the name of their corresponding database connection. 

If you have the time to provide a PR for this please proceed - I'm not sure I can find the time to implement it myself right now ...

**Comment by chrisclark** [comment]
Hey folks - I just roughed out a really simple approach to this.

Basically - explorer just looks at all available DBs configured in settings and allows you to pick one from a drop-down. It then saves the DB name as a string on the Query model.

There's a bunch of cleanup to do (don't show the form, if there is only 1 DB, proper defaulting, tests, UX cleanup, implementing it for the Playground, etc.) but I think it's a nice start.

I'm also going to add a setting to restrict the available explorer DBs to a subset of all the defined ones (since, like in my case, I have a separate connection defined for Explorer that is read-only and I wouldn't want people to have the ability to select the 'default' connection). But out of the box it'll just look at all available connections.

Thoughts? You can pull down the branch and see it in action via the test project. Would love feedback and I'm happy to change approaches, as this represents only like 45mins of work so far.

**Comment by chrisclark** [comment]
![screen shot 2016-11-04 at 12 54 21 pm](https://cloud.githubusercontent.com/assets/693700/20020292/d90812f8-a28d-11e6-9292-f90d17a376d4.png)

Here's what it looks like in the branch.

**Comment by jameswinegar** [comment]
I was talking with one of my dev's yesterday and they were going to do the exact same thing and submit a PR. Glad we had roughly the same idea.

**Comment by spapas** [comment]
Hell @chrisclark this is really great! Being able to relate each query with the connection would be very helpful - thank you!

Two things I'd like to add:

- This is related to #245 i.e you should be able to select the connection for the schema preview
- Restricting/selecting which connections will be available is a nice addition - however I think that adding a way to configure the triplet connection / group / permission (with permission being edit queries / view queries / none) would be even more useful. So we'd be able to define groups of users that are able to query a connection but don't have access to the other connections.

**Comment by chrisclark** [comment]
Alright folks -- I just merged multiple connection support into master...just a short 27 months after it was requested!

I think it's a fairly robust implementation; though it does not cover what @spapas requested in terms a security model (yet).

The entire security model needs an overhaul, but until then, this is in, and has been used successfully by my company in production under heavy load for the past month or so. But if maintaining this project has taught me anything, it's that everyone uses this tool slightly differently, so please do report issues if you find them.

I'll probably let this set of changes cook for another 2 weeks, and then release to PyPi.
