### ISSUE TITLE
Feature Request: EXPLORER_SCHEMA_INCLUDE_APPS

### ISSUE THREAD

**Issue by raiderrobert** [groveco/django-sql-explorer#174]
I literally only have one app that I want people to run reports against. But I have like 50 apps.  So I'd like to have EXPLORER_SCHEMA_INCLUDE_APPS as a new setting.

On top of this, I really think you should have an include rather than an exclude as a default, since that's the Django way (configuration over convention) and follows how they handle forms and other things. But that's just my opinion.

**Comment by chrisclark** [comment]
I hear ya. I probably will not get around to implementing this feature, but if you want to submit it as a PR, and can do it in a way that isn't confusing, and is backwards compatible, I'm open to it philosophically.

At some point I'd like to rewrite the schema explorer to generically extract DB schema info, rather than relying on Django models to do it. That would make Explorer a django-based, but system-agnostic SQL exploration tool. If/when I get around to that, I'd want to revisit how tables are included/excluded from the schema explorer.

**Comment by jproffitt** [comment]
Looking at how django handles `ModelForm.Meta.fields` and `ModelForm.Meta.exclude`, I found that django will include all fields listed in `fields` (or all the fields on the model if `fields` is not set), minus any fields in `exclude`. 

So, I recommend we introduce the setting `EXPLORER_SCHEMA_INCLUDE_APPS`, which is defaulted to `None`, meaning include all apps.

The `EXPLORER_SCHEMA_EXCLUDE_APPS` setting will continue to work just like it does now, only it will exclude starting with the list in `EXPLORER_SCHEMA_INCLUDE_APPS`, if any.

This is backwards compatible because if you don't set `EXPLORER_SCHEMA_INCLUDE_APPS`, nothing changes.
