### ISSUE TITLE
[Question/Enhancement]

### ISSUE THREAD

**Issue by mykljohn** [groveco/django-sql-explorer#195]
Is there any way to sent the Query to the printer?  If not that would be nice.

Also adding the Parameters to the Header.

**Comment by chrisclark** [comment]
I would recommend downloading the query, opening it in Excel, and printing from there. I also have a branch going to general-purpose exporting; we could potentially add a PDF export option which would make printing easier. That's probably the right approach, rather than writing special functionality to print from the browser. If you'd like, you can file an issue to request PDF export and if there's enough demand, I or someone else might get to it.
