### ISSUE TITLE
UI Bug: Schema Viewer seems to Duplicate Schemas

### ISSUE THREAD

**Issue by raiderrobert** [groveco/django-sql-explorer#212]
A picture is worth a thousand words, so here's what I see in the schema viewer when I have authtools installed.

![screen shot 2016-07-12 at 7 49 52 am](https://cloud.githubusercontent.com/assets/806571/16766005/3c30870e-4805-11e6-8b53-4dce40cc9ed7.png)

If you look in the db itself, you'll see that there is only one authtools_user_groups. So somehow these are being duplicated.

![screen shot 2016-07-12 at 9 14 25 am](https://cloud.githubusercontent.com/assets/806571/16768158/142c202c-4811-11e6-9d5f-3010839fcb21.png)

Using Postgres version:
```PostgreSQL 9.3.9 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4, 64-bit```

Here's pip freeze below.

```
alpaca==1.3.4
amqp==1.4.9
anyjson==0.3.3
Babel==2.3.4
backports.ssl-match-hostname==3.5.0.1
billiard==3.3.0.23
celery==3.1.23
certifi==2016.2.28
contextlib2==0.5.3
deployment==0.3.7
diff-match-patch==20121119
dj-inmemorystorage==1.4.0
Django==1.9.7
django-authtools==1.5.0
django-autoslug==1.8.0
django-bootstrap3==7.0.0
django-celery==3.1.17
django-classy-tags==0.7.2
django-compat==1.0.8
django-debug-toolbar==1.4
django-debug-toolbar-template-timings==0.6.6
django-extra-views==0.7.1
django-formset-js==0.5.0
django-hstore==1.4.1
django-import-export==0.4.1
django-jquery-js==2.1.4
django-localflavor==1.2
django-parsley==0.6
django-recaptcha==1.0.5
django-sekizai==0.9.0
django-sql-explorer==0.9.2
djangorestframework==3.3.1
easy-thumbnails==2.2.1
ecdsa==0.13
enum34==1.1.6
Fabric==1.11.1
flower==0.9.1
funcsigs==1.0.2
futures==3.0.5
hypothesis==3.4.0
Jinja2==2.8
kombu==3.0.35
MarkupSafe==0.23
mock==1.3.0
model-mommy==1.2.6
paramiko==1.17.0
pbr==1.10.0
Pillow==3.0.0
psycopg2==2.6.1
pycrypto==2.6.1
python-dateutil==2.4.2
pytz==2016.4
raven==5.20.0
redis==2.10.5
requests==2.10.0
six==1.10.0
sqlparse==0.1.19
stripe==1.28.0
tablib==0.11.2
tornado==4.2
unicodecsv==0.14.1
```

**Comment by chrisclark** [comment]
Yep. I've seen this too. It's because the schema view is built by introspecting the models in each app:

https://github.com/groveco/django-sql-explorer/blob/master/explorer/utils.py#L26

There's some issue here where many to many fields get double-counted, or something. I haven't taken the time to nail it down.

Frankly I think the real solution here is to write some custom SQL to generate the schema directly from the DB metadata rather than relying on Django introspection. That would solve issues like this, and decouple the app from Django-based DBs so it could be an effective query tool against arbitraray sql dbs.
