### ISSUE TITLE
UX Enhancement: Allow Users to Expand/Collapse Schemas

### ISSUE THREAD

**Issue by raiderrobert** [groveco/django-sql-explorer#214]
The following is a little nit picky, but follow me on this. For large databases, you could have lots of schemas, since the search only looks at the schema names, it would make sense to allow for all the fields below to be collapsed by default, so you don't have to scroll for a while.

![screen shot 2016-07-12 at 12 07 37 pm](https://cloud.githubusercontent.com/assets/806571/16774260/3d7f77fe-4829-11e6-8618-21072bd37c0c.png)

**Comment by chrisclark** [comment]
Maybe the thing to do is render anchor links for each table, and sort of have a 'table of contents' at the top of the schema explorer. Clicking on the name of a table jumps you right to that table. I'd prefer something like that to toggling because it doesn't force another click. If someone wants to search for something directly, they can still do that very quickly without data being hidden behind a toggle.

**Comment by jproffitt** [comment]
What do you think about having a "collapse all" button at the top? So they would still all be expanded by default, but you could collapse them all with one click. And also be able to collapse/expand each one individually.

**Comment by chrisclark** [comment]
Works for me. I don't have strong opinions about this feature as long as it doesn't worsen the experience for users who don't have large schemas.

**Comment by chrisclark** [comment]
It suddenly clicked for me that you guys work at the same place :) This is making all sorts of sense now!

**Comment by raiderrobert** [comment]
@chrisclark yeah, I've been super busy, so I asked @jproffitt to take the task from me.
