### ISSUE TITLE
UX Enhancement: Allow users to auto-insert table and columns names by double clicking in the schema helper

### ISSUE THREAD

**Issue by jproffitt** [groveco/django-sql-explorer#223]
I find myself constantly double clicking to select an item in the schema helper, then copy and pasting it into the SQL editor. It might be nice if you could just double click, and it would automatically insert it into the editor wherever the cursor is.

Do you think this would be a good idea?

**Comment by chrisclark** [comment]
Great idea! Not sure how to implement it across iframes, but sounds like
you do.

On Jul 29, 2016, at 8:48 AM, Jared Proffitt <notifications@github.com>
wrote:

I find myself constantly double clicking to select an item in the schema
helper, then copy and pasting it into the SQL editor. It might be nice if
you could just double click, and it would automatically insert it into the
editor wherever the cursor is.

Do you think this would be a good idea?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/groveco/django-sql-explorer/issues/223>, or mute the
thread

**Comment by chrisclark** [comment]
@jproffitt hey man -- this feature has driven me absolutely bananas over the past couple of months, so I'm taking it out. It sounds great in theory, but in practice I've found it's very unusual that my cursor is in the exact same place that i need to insert the field name, so it would actually be more convenient to select it, and then i can paste it where needed. Not sure if you've found the same thing, but hopefully you have and I'm not removing a beloved feature here!

**Comment by jproffitt** [comment]
@chrisclark I do find it useful, but if you don't think it's a good idea, then go ahead. Or perhaps make it a setting to toggle the feature on or off? Or maybe move the functionality to a small button on the left so that you can still double click to select?
