### ISSUE TITLE
Enhancement/suggestion : Collapsing sql panel 

### ISSUE THREAD

**Issue by m-libbrecht** [groveco/django-sql-explorer#244]
Hi,

I came just across django-sql-explorer. I have a use case where I'd want to hide the SQL query panel for SQL ignorant users.  Without major changes this could be accomplished e.g. by wrapping it into a jQuery Accordion panel. The Accordion could be collapsed by default depending on a setting. 

I suppose the enhancement of paginating the query preview has somewhat the same goal of hiding the complexity of the underlying SQL ?

**Comment by chrisclark** [comment]
Yeah, this is a great idea. Definitely open to a pull request for this. Off the top of my head it seems reasonable to cookie the user with the collapsed/uncollapsed toggle so we know how to render each query view without them having to toggle every one.

**Comment by m-libbrecht** [comment]
It seems to me that a more elegant solution is to make use of the CSS display property :  see attached file [django-sql-explorer.pdf](https://github.com/groveco/django-sql-explorer/files/1220076/django-sql-explorer.pdf)

1) in the template **explorer/templates/explorer/query.html:**

A) HTML
- wrap the sql-panel and the form-group hereafter in a div that you give a class name hidable-sql
- add the text SQL on the right above the sql-panel

B)  JS:

Add the following code to the {% block sql_explorer_scripts %}:

`        $('.sql-show-toggle').click(function () {
            $('.hidable-sql').slideToggle('slow');
        });`

2.) Add the following CSS to the end of **explorer/static/explorer/explorer.css:**

`.hidable-sql {
    display:none;
}
`
This will hide the sql-panel and form-group by default. Clicking on SQL will toggle the visibility of sql-panel and form-group.

That would be all.

**Comment by marksweb** [comment]
@m-libbrecht We're a few years down the line, but I like this idea, so I've had a play around.

Very similar to what you've suggested, apart from `display: none` can't be done in the markup or CSS because it stops the editor widget from initialising properly. So the javascript does a `hide()` on page load for anything with a certain class.

So I'd propose a flow like this...

New query

<img width="1182" alt="Screenshot 2020-12-08 at 09 56 35" src="https://user-images.githubusercontent.com/1461191/101468739-b6f07e00-393b-11eb-80b9-20c2b681a3e4.png">

Opening an existing query

<img width="1186" alt="Screenshot 2020-12-08 at 09 54 45" src="https://user-images.githubusercontent.com/1461191/101468775-c4a60380-393b-11eb-8ba8-0d432b2d2b09.png">

Toggled SQL

<img width="1186" alt="Screenshot 2020-12-08 at 09 55 00" src="https://user-images.githubusercontent.com/1461191/101468817-d12a5c00-393b-11eb-916d-bbc3ee978358.png">

**Comment by chrisclark** [comment]
My preference would be to do it by adding an additional glyph on the top right. E.g. something like:
![image](https://user-images.githubusercontent.com/693700/101497843-425c1600-3920-11eb-9911-20c236f9e663.png)

I don't think a pure UI toggle should appear as a top-level button.

**Comment by marksweb** [comment]
@chrisclark sure, that looks neat.

I've switched to that with some jquery to add/remove classes & slide `.panel-content`

<img width="1163" alt="Screenshot 2020-12-08 at 16 52 17" src="https://user-images.githubusercontent.com/1461191/101515102-e6bc7780-3975-11eb-891d-4558c8fded52.png">
