### ISSUE TITLE
Email query results icon not visible

### ISSUE THREAD

**Issue by anirvan-majumdar** [groveco/django-sql-explorer#272]
Hi,  

First up, thanks so much for making this wonderful tool and ensuring that it's delightfully simple to integrate!  

I've got the setup working on my project, and almost everything seems to be working as expected. One of the things I haven't been able to figure out however, is the "email" icon in the query listing window to email the results of a query. Even in the screenshots in your readme, I wasn't able to see where the icon is.

The documentations says that it should be in the query _listing_ window - but I can't find it in either the listing window or the query details window. 

Have I missed out configuring something here?

Thanks!

**Comment by chrisclark** [comment]
Hi @anirvan-majumdar -- thanks for the note. You will need to enable asynchronous tasks via the EXPLORER_TASKS_ENABLED setting for this to appear. Since the email functionality depends on Celery, tasks must be enabled. I believe there is some documentation around this. And you will of course need the EMAIL_HOST setting in django configued, as well as the S3 settings.
