### ISSUE TITLE
Bug: does not work with column name updated_at

### ISSUE THREAD

**Issue by WarmongeR1** [groveco/django-sql-explorer#274]
Hi all,

I have simple sql request -
 
```sql
SELECT updated_at FROM table_name;
```

I use default settings for django-sql-explorer.
As result, I have error - "Query failed the SQL blacklist: UPDATE"

http://www.awesomescreenshot.com/image/2048618/7662bfcd9da4736d9ca47ff8ea0850c3

**Comment by anirvan-majumdar** [comment]
+1

**Comment by chrisclark** [comment]
Looks like 'updated' was added to the default whitelist in this commit:

https://github.com/groveco/django-sql-explorer/commit/3b58a1c8b52d1369cdb0b8d1b12f02fcfcb75c59#diff-4621771ce289f14e1f26e3efb023854f

Kind of embarrassing I haven't done a release since then...

I'm releasing tomorrow, but in the mean time you can just add `EXPLORER_SQL_WHITELIST = ['UPDATED', 'CREATED', 'DELETED' ...]` to your django settings file to work around.
