### ISSUE TITLE
readonly is not a valid Django DB connection.

### ISSUE THREAD

**Issue by charleshan** [groveco/django-sql-explorer#351]
The documentation suggests the following settings:
```
EXPLORER_CONNECTIONS = { 'Default': 'readonly' }
EXPLORER_DEFAULT_CONNECTION = 'readonly'
```
However this results in an error:
```
django.core.exceptions.ImproperlyConfigured: EXPLORER_CONNECTIONS contains (Default, readonly), but readonly is not a valid Django DB connection.
```

From doing a quick search (https://github.com/groveco/django-sql-explorer/issues/306), it looks like the solution is changing the settings to:
```
EXPLORER_CONNECTIONS = { 'Default': 'default' } 
EXPLORER_DEFAULT_CONNECTION = 'default'
```

Is this is the correct (safe) solution? If so, we should update the documentation.

**Comment by spapas** [comment]
Actually the correct thing to do from a security standpoint is to add *another" read-only connection to your django settings. So beyond 'default' you'll have a 'readonly' key to your `DATABASES` settings dictionary (that would connect with a user that has read-only access to the tables). 

However, the README definitely needs some updating because I can see the following phrase right after `EXPLORER_CONNECTIONS` is explained:

```
The first setting lists the connections you want to allow Explorer to use. The keys of the connections dictionary are friendly names to show Explorer users, and the values are the actual database aliases used in settings.DATABASES. It is highly recommended to set
```

this definitely has something missing and needs to be properly completed!

**Comment by charleshan** [comment]
Any hints on how to achieve this? Are we supposed to create a read only user in the database (PostgreSQL in my case)? Something like [this](https://gist.github.com/oinopion/4a207726edba8b99fd0be31cb28124d0) and add it to the `DATABASES` settings dictionary?

**Comment by spapas** [comment]
Yes that would be the correct way to go for creating a read only connection. Also since that new user would be completely different from the one your django app uses, you may give that user view permission only to specific tables so you may omit some tables that are used for internal django work (i.e migrations, sessions etc)

**Comment by zehawki** [comment]
Is anyone actively maintaining this project? I saw a half complete sentence "It is highly recommended to set" in https://pypi.org/project/django-sql-explorer/. From there I came here, and saw the same in the docs. Then went thru the install steps, and hit the problem as described in this issue, and see that this has been pointed out 2 years ago!

Requesting the authors / maintainers to update docs and bring in the great info from @spapas into the docs.

**Comment by marksweb** [comment]
@zehawki I became a maintainer a few days ago to try to get things rolling, bring django 3 support etc.

We're nearly there with thanks to a fair few people actively contributing. And @spapas has just updated the readme in #406 which I think closes this ticket.

Talking of docs, there is a branch with the very beginning of a sphinx setup. I think the README needs refactoring to be a bit more basic in itself with the vast majority of it's details put into sphinx.
