### ISSUE TITLE
psycopg2 2.8 compatibility

### ISSUE THREAD

**Issue by lexnjugz** [groveco/django-sql-explorer#367]
sequence index must be integer, not 'slice'

**Comment by djw27** [comment]
We ran into this same issue and it looks like it was fixed in this commit here: https://github.com/django/django/commit/5efaf078f7609a8c95045bcfdab0ba256b5449bf

The issue was in this line: https://github.com/django/django/commit/5efaf078f7609a8c95045bcfdab0ba256b5449bf#diff-7f14932a08ce1dbba14da7433e47f9fcL80

I don't the linked fix was for this specific issue, so I wonder if this is actually more to do with a specific python version. Specifically it's the unpacking and slicing of `line` which causes this error - `*line[0:6]` in `return [FieldInfo(*line[0:6], *field_map[line.name]) for line in cursor.description]`

If I change this to `[*line][0:6]` then I no longer get the error - return [FieldInfo([*line][0:6], *field_map[line.name]) for line in cursor.description].

Running Python 3.6.5 for reference.

**Comment by djw27** [comment]
Upgrading django to 2.2.1 fixed this issue for me

**Comment by marksweb** [comment]
Closing based on the above.
