### ISSUE TITLE
Django 3.0 support?

### ISSUE THREAD

**Issue by nitish-squadrun** [groveco/django-sql-explorer#392]
Right now when I install this library in my Django 3.0 project, I get the following error:
`ImportError: cannot import name 'render_to_response' from 'django.shortcuts' (...../lib/python3.7/site-packages/django/shortcuts.py)`

`render_to_response` was deprecated in Django 2.0 and removed from Django 3.0. Can someone please deploy a fix for this?

**Comment by nitish-squadrun** [comment]
Looks like the repo is updated to include 3.0 support but a new release has not been added to pip

**Comment by johnnybhojwani** [comment]
Thanks for sharing this nitish! I was stuck with the same issue for hours and tried all sorts of things. But when you said that the repo was updated but pip was not, that helped me tremendously. I just used the git link in my requirements.txt instead of pip and it works great, so thanks again!

**Comment by robertofd1995** [comment]
Same issue, I created the PR to adapted to Django 3.0, @chrisclark could you publish the new version?

**Comment by tdarnett** [comment]
Hey @robertofd1995, your link is now resolving to a 404 which is impacting our pip install. @chrisclark any updates on when this PR can be published into the next version bump?

**Comment by michaeljohnbarr** [comment]
There's a further issue that we are facing at my workplace now. The `setup.py` has the line:

```python
install_requires=[
   'Django>=2.2,<=3.0.5',
   ...
]
```

...which does not allow us security or bugfix updates beyond Django 3.0.5. As of the date of this comment, the latest version of Django is 3.1. The workaround posted above doesn't work if you want to be on that version and are using a dependency resolver such as `pipenv` or `poetry`.

At this point, the only option that we have are:
1. To fork this repository in our organization and manage it ourselves.
2. Accept being limited to Django 3.0.5.
3. Downgrade to Django 2.2 for the LTS release which is supported by the only tagged version of django-sql-explorer (version 1.1.3).

Ultimately, we could really use a tagged release in PyPi for version 1.1.14, that also supports Django 3.0+. I'm certain that there was a reason for restricting the upper limit of the version of Django, but I'd really like to see that removed (even if only temporarily) so that anyone that wants to use Django 3.0 or Django 3.1 can.

**Comment by marksweb** [comment]
What's happening with the project? PRs have been merged that appear to bring 3.1 support but they're unreleased.

I'm setting up a new project with an internal admin app which integrates this app and obviously won't start a new project in anything less than 3.1.

Can I assist in package maintenance?

**Comment by Anton-Shutik** [comment]
@chrisclark Could you pls make a release  ?

**Comment by marksweb** [comment]
@Anton-Shutik I've got the ability to release now, so need to tie up the loose ends, get some conflicts resolved on the PRs & then look at a release.

Chris also mentioned dropping Python 2 support. So I think we need a new major version, dropping python 2 and older django support.

**Comment by hugovk** [comment]
From https://www.djangoproject.com/download/:

![image](https://user-images.githubusercontent.com/1324225/95362471-ccfba700-08d6-11eb-941d-fd3880df35eb.png)

Drop 2.1 and earlier?

**Comment by marksweb** [comment]
@hugovk Yeah I think that's the best move. In master `setup.py` already has `>=2.2.14` I think & travis is failing on 1.11 due to this "transition phase".

I'll have a look at tidying things up & merging the #403 later on.

From what I've tested, it works in django 3 already even though there may be django 3 related PRs unmerged.

**Comment by marksweb** [comment]
Ok, I think it's nearly ready for release.

I'm going to run the master branch in a couple of projects for a proper test. If people could do the same, that'd be great.

```
-e git+https://github.com/groveco/django-sql-explorer@master#egg=django-sql-explorer
```

**Comment by spapas** [comment]
I have integrated the master branch to a Django 3.1.2 app and it seems to be working without  problems. Also the getting started part of the readme is solid.

I haven't been able to test it extensively though (but I'll do some more tests tomorrow) and I don't use celery so I can't test that functionality at all.

**Comment by marksweb** [comment]
Excellent, thank you @spapas 

I'm just doing some further refactoring - turning the views file into a nicely organised module, for example. Going to look at also making the excel export only show up if xlsxwriter is available to avoid that causing server errors.

**Comment by marksweb** [comment]
Closing this following the 2.0 release
