### ISSUE TITLE
Celery 5.0 support

### ISSUE THREAD

**Issue by jottunn** [groveco/django-sql-explorer#437]
Any plans for it?

**Comment by marksweb** [comment]
@jottunn Still using celery 4 on all projects here. Although I don't actually use any of the celery features of this app.

What would celery 5 mean for the project?

[Their change log](https://github.com/celery/celery/blob/master/Changelog.rst#500) basically just looks like they've dropped for support for all sorts.

**Comment by marksweb** [comment]
Looking into celery 5 implementation along with `django-celery-results` to replace `djcelery`. I'm not yet clear how third party apps should define tasks in celery 5.

No longer is it valid to do;

```
from celery import task


@task
def my_task()
    pass
```

You now have to import a task from the project's celery instance which I gather to be along the lines of;

```
from project import celery


@app.task
def my_task():
    pass
```

But it's not for third party packages to be defining the instance of celery, the broker etc. That's all for the project which installs the application.

I'm hoping there's some way to integrate settings to get around this, but the docs are focused on the perspective of the project author, rather than the package author.

**Comment by lawson89** [comment]
I think celery 5 it's @shared_task, looking into this now

**Comment by marksweb** [comment]
This is now being discussed in #493
