### ISSUE TITLE
Possible to do math on dates?

### ISSUE THREAD

**Issue by toddmickel** [groveco/django-sql-explorer#460]
I am attempting to create a query that will allow you to select records with a date between today's date and 12 months from now.  

I was able to discover that current_date gives today's date:
`SELECT date(current_date)`
returns:
`2021-10-02`

But I cannot find any functionality that allows me to calculate a date 12 months from now:
`SELECT (current_date - interval '12 months')` and
`SELECT (current_date - interval 12 months)`

return:
`near "12 months": syntax error`

Since it's working with a MySQL database, I tried:
`SELECT DATE_ADD(current_date, interval 12 month);`
returns:
`near "12": syntax error`

So I'm guessing INTERVAL doesn't work with Django SQL Explorer.  Is there another way to do date math?

Thanks,
-Todd

**Comment by marksweb** [comment]
Hi @toddmickel 

There's isn't [to my knowledge] any SQL that django-sql-explorer won't support, because it just runs your queries on your database.

Having said that, it won't allow you to do anything that's on the blacklist; https://django-sql-explorer.readthedocs.io/en/latest/settings.html#sql-blacklist

I've just tested your query on a MySQL server and I'm able to run it;

```
SELECT DATE_ADD(NOW(), INTERVAL 12 MONTH)

> Oct. 2, 2022, 8:07 p.m.
```

![screencapture-toughmudder-ukie-realbuzz-admin-sql-explorer-play-2021-10-02-21_08_01](https://user-images.githubusercontent.com/1461191/135730639-5745f027-1895-4578-857d-d6b24b56509c.png)

**Comment by toddmickel** [comment]
Hi @marksweb ,

Thank you for the prompt response -- I'm not sure where I was getting it wrong before, but it seems to be working now.  I appreciate the reply!
